# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
# Site title
title: Welcome to visits Archer's blog
#Site description
description: > # this means to ignore newlines until next variable
  Write an awesome description for your new site here. You can edit this
  line in _config.yml. It will appear in your document head meta (for
  Google search results) and in your feed.xml site description.

#baseurl: 网站根路径
baseurl: "" # the subpath of your site, e.g. /blog
#Host page url
url: "https://archerli.github.io" # the base hostname & protocol for your site, e.g. http://example.com
#Jekyll Build configuration

source: _posts
#从 _posts 目录中读取数据

destination: _site
#将生成的文件写入到 _site 目录中

include: ['.htaccess', '_includes']


#联系人信息
email: liyaqingatamoi@gmail.com
author: archerli
github_username:  archerli

# Build settings
markdown: kramdown
#permalink: 配置文章的永久链接
#permalink: date 表示 permalink: /:categories/:year/:month/:day/:title.html
permalink: /blog/:categories/:year/:month/:day/:title.html
paginate: 10

#主题样式
theme: minima

highlighter: rouge
excerpt_separator: "\n\n"
  
analytics:
    google:
    tracking_id: UA-80557370-2

gems: ['jekyll-feed']
exclude: ['README.md', 'Gemfile.lock', 'Gemfile', 'Rakefile']

